# Generated by Django 5.2.17 on 2026-09-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('disaster', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
